Make rendering algorithm more robust (#272)

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,4 +1,4 @@
-  #
+#
 # GitHub runner workflow for building, verifying and testing the XVM repo.
 #
 # TODO: Add periodic workflows (that can be manually triggered /w workflow_disspatch and also run through a cron file)
@@ -149,42 +149,44 @@ jobs:
         run: |
           ./gradlew ${{ env.gradle_options }} manualTests:runParallel
 
-  publish-snapshot:
-    name: Publish to GitHub packages iff snapshot + non-redundant build platform + branch is master
-    needs: build-verify
-    runs-on: ubuntu-latest
-    #if: ${{ (github.ref == 'refs/heads/master') }}
-    steps:
-      # Check out current repository
-      - name: Fetch Sources
-        uses: actions/checkout@v4
-
-      # Set up Java environment for the next steps
-      - name: Setup Java
-        uses: actions/setup-java@v4
-        with:
-          distribution: zulu
-          java-version: ${{ env.java_version }}
-
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@v4
-        with:
-          cache-disabled: ${{ github.ref == 'refs/heads/master' }}
-          cache-read-only: false
-          gradle-version: ${{ env.gradle_version }}
-
-      - name: Dump environment info
-        shell: bash
-        run: |
-          echo "*** Branch (github.ref)    : ${{ github.ref }}"
-          echo "*** Commit (github.sha)    : ${{ github.sha }}"
-          echo "*** Runner OS              : ${{ runner.os }}"
-          echo "*** Java system properties :" 
-          java -XshowSettings:properties --version
-
-      - name: Create or Update Snapshot (if pushed to 'master', or env.always_publish_snapshot is true)
-        if: ${{ (env.always_publish_snapshot == 'true') || (github.ref == 'refs/heads/master') }}
-        shell: bash
-        run: |
-          ./gradlew ${{ env.gradle_options }} xdk:ensureTags -PsnapshotOnly=true
-          ./gradlew ${{ env.gradle_options }} publishRemote -PsnapshotOnly=true
+# TODO Marcus: this fails intermittently 
+#  publish-snapshot:
+#    name: Publish to GitHub packages iff snapshot + non-redundant build platform + branch is master
+#    needs: build-verify
+#    runs-on: ubuntu-latest
+#    #if: ${{ (github.ref == 'refs/heads/master') }}
+#    steps:
+#      # Check out current repository
+#      - name: Fetch Sources
+#        uses: actions/checkout@v4
+#
+#      # Set up Java environment for the next steps
+#      - name: Setup Java
+#        uses: actions/setup-java@v4
+#        with:
+#          distribution: zulu
+#          java-version: ${{ env.java_version }}
+#
+#      - name: Setup Gradle
+#        uses: gradle/actions/setup-gradle@v4
+#        with:
+#          cache-disabled: ${{ github.ref == 'refs/heads/master' }}
+#          cache-read-only: false
+#          gradle-version: ${{ env.gradle_version }}
+#
+#      - name: Dump environment info
+#        shell: bash
+#        run: |
+#          echo "*** Branch (github.ref)    : ${{ github.ref }}"
+#          echo "*** Commit (github.sha)    : ${{ github.sha }}"
+#          echo "*** Runner OS              : ${{ runner.os }}"
+#          echo "*** Java system properties :" 
+#          java -XshowSettings:properties --version
+#
+#      - name: Create or Update Snapshot (if pushed to 'master', or env.always_publish_snapshot is true)
+#        if: ${{ (env.always_publish_snapshot == 'true') || (github.ref == 'refs/heads/master') }}
+#        shell: bash
+#        run: |
+#          ./gradlew ${{ env.gradle_options }} xdk:ensureTags -PsnapshotOnly=true
+#          ./gradlew ${{ env.gradle_options }} publishRemote -PsnapshotOnly=true
+#
