Release tag flow

diff --git a/.github/workflows/install-and-check.yml b/.github/workflows/install-and-check.yml
--- a/.github/workflows/install-and-check.yml
+++ b/.github/workflows/install-and-check.yml
@@ -9,10 +9,13 @@ on: push
 
 env:
   ORG_GRADLE_PROJECT_xtcPluginOverrideVerboseLogging: true
+
   ORG_GRADLE_PROJECT_includeBuildManualTests: true
   ORG_GRADLE_PROJECT_includeBuildAttachManualTests: true
+
   ORG_XTCLANG_JAVATOOLS_SANITY_CHECK_JAR: true
   GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: false
+
   gradle_options: --stacktrace --warning-mode all --console verbose
 
 #concurrency:
@@ -32,9 +35,10 @@ jobs:
       minor: ${{ steps.properties.outputs.minor }}
       patch: ${{ steps.properties.outputs.patch }}
       snapshot: ${{ steps.properties.outputs.snapshot }}
-      tag_new: $${ steps.properties.outputs.tag_new }}
-      tag_last: $${ steps.properties.outputs.tag_last }}
-      changelog: ${{ steps.properties.outputs.changelog }}
+      tag_last_release: ${{ steps.properties.outputs.tag_last_release }}
+      tag_new_release: ${{ steps.properties.outputs.tag_new_release }}
+      tag_next_release: ${{ steps.properties.outputs.tag_next_release }}
+      #changelog: ${{ steps.properties.outputs.changelog }}
 
     steps:
       - name: Fetch Sources
@@ -42,40 +46,55 @@ jobs:
 
       - name: Export Properties
         id: properties
-        shell: bash
+        #shell: bash
         run: |
-          function parse_version() {
-            local _re='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
-            local _match="s#$_re#\\$1#"
-            echo $xdk_version | sed -e $_match
-          }
-
+          # Parse XDK version from VERSION file in repo root
           xdk_version="$(cat ./VERSION)"
-          if [[ "$xdk_version" == *SNAPSHOT ]]; then
-            echo "snapshot=true" >> $GITHUB_OUTPUT
-          fi          
-          xdk_version="${xdk_version%-SNAPSHOT}"
+          echo "xdk_version from disk: $xdk_version"
           
-          major="$(parse_version 1)"
-          minor="$(parse_version 2)"
-          patch="$(parse_version 3)"
-          tag_last="$(git describe --tags --abbrev=0)"          
+          # Check if the version is a snapshot (will lead to publication for any push to master)
+          if [[ "$xdk_version" == *SNAPSHOT ]]; then
+            echo "snapshot identified"
+            echo "snapshot=true" >> $GITHUB_OUTPUT
+          fi
 
+          # Strip version string suffix (i.e. remove -SNAPSHOT, -M1, etc)          
+          xdk_version="${xdk_version%-SNAPSHOT}"                   
+          
+          # Parse the major, minor and patch version
+          _re='[^0-9]*\([0-9]*\)[.]\([0-9]*\)[.]\([0-9]*\)\([0-9A-Za-z-]*\)'
+          major=$(echo "$xdk_version" | sed -e "s#$_re#\1#")
+          minor=$(echo "$xdk_version" | sed -e "s#$_re#\2#")
+          patch=$(echo "$xdk_version" | sed -e "s#$_re#\3#")
+
+          # Set up tags, where applicable
+          tag_last_release=$(git describe --tags --abbrev=0)
+          tag_this_release="v$xdk_version"
+          tag_next_release="v$major.$minor.$((patch + 1))-SNAPSHOT"
+          echo "tag:"
+          echo "  last=$tag_last_release"
+          echo "  this=$tag_this_release"
+          echo "  next=$tag_next_release"
+          
+          # Write resolved variables to output
           echo "version=$xdk_version" >> $GITHUB_OUTPUT
           echo "major=$major" >> $GITHUB_OUTPUT
           echo "minor=$minor" >> $GITHUB_OUTPUT
           echo "patch=$patch" >> $GITHUB_OUTPUT
-          echo "tag_new=v$xdk_version" >> $GITHUB_OUTPUT
-          echo "tag_last=$tag_last" >> $GITHUB_OUTPUT          
+          echo "tag_last_release=$tag_last_release" >> $GITHUB_OUTPUT
+          echo "tag_this_release=$tag_this_release" >> $GITHUB_OUTPUT
+          echo "tag_next_release=$tag_next_release" >> $GITHUB_OUTPUT
+
           # TODO: changelog          
 
   build:
-    name: Build installDist
-    needs: [ setup ]
+    name: Build 'installDist'
+    needs: setup
     strategy:
       matrix:
         os: [ ubuntu-latest, windows-latest ]
     runs-on: ${{ matrix.os }}
+
     steps:
       - name: Fetch Sources
         uses: actions/checkout@v4
@@ -93,7 +112,7 @@ jobs:
       - name: Setup Gradle and Gradle Cache
         uses: gradle/actions/setup-gradle@v3
         with:
-          gradle-home-cache-cleanup: true
+          #gradle-home-cache-cleanup: true
           cache-read-only: false
 
       - name: Gradle Wrapper Validation
@@ -106,39 +125,72 @@ jobs:
           echo "*** XDK_VERSION_MAJOR: ${{ needs.setup.outputs.major }}"
           echo "*** XDK_VERSION_MINOR: ${{ needs.setup.outputs.minor }}"
           echo "*** XDK_VERSION_PATCH: ${{ needs.setup.outputs.patch }}"
-          echo "*** XDK_VERSION_TAG: $$${{ needs.setup.outputs.tag_new }}"
-          echo "*** XDK_VERSION_TAG_LAST: ${{ needs.setup.outputs.tag_last }}"
+          echo "*** XDK_VERSION_LAST_TAG: ${{ needs.setup.outputs.tag_last_release }}"
+          echo "*** XDK_VERSION_THIS_TAG: ${{ needs.setup.outputs.tag_this_release }}"
+          echo "*** XDK_VERSION_NEXT_TAG: ${{ needs.setup.outputs.tag_next_release }}"
+
+      - name: Check for Tag
+        run: |          
+          echo "Checking for tag ${{ needs.setup.outputs.tag_this_release }}"
+          git tag -l ${{ needs.setup.outputs.tag_this_release }}
+          existing_tags=$?        
+          if [[ $existing_tags -eq 0 ]]; then
+            echo "ERROR: Tag for this release already exists $tag"
+            exit 1
+          fi
+          echo "*** Tag ${{ needs.setup.outputs.tag_this_release }} does not exist yet; proceeding with buuild."
+
+      - name: Forbid merges
+        run: |
+          echo "TODO: Here we need to check whether someone has added merges since we last tagged the release."
+          # (and fail)
 
       - name: Execute Gradle installDist
         run: ./gradlew ${{ env.gradle_options }} installDist
 
       - name: Execute Gradle manualTest sanity checks
+        if: ${{ false }}
         run: |
           ./gradlew ${{ env.gradle_options }} manualTests:runXtc
           ./gradlew ${{ env.gradle_options }} manualTests:runOne -PtestName=TestMisc
           ./gradlew ${{ env.gradle_options }} manualTests:runTwoTestsInSequence
           ./gradlew ${{ env.gradle_options }} manualTests:runParallel
 
-      # Always publish a snapshot on push (TODO: change to push to master, not just push)
-      - name: XDK Publish Snapshot to xtclang.org GitHub Maven Packages.
+      - name: Publish XDK Snapshot
         if: ${{ needs.setup.output.snapshot == 'true' }}
-        run: echo "*** XDK_VERSION Publishing SNAPSHOT" && ./gradlew publishRemoteSnapshot
         env:
           ORG_XTCLANG_REPO_GITHUB_USER: xtclang-bot
           ORG_XTCLANG_REPO_GITHUB_TOKEN: ${{ secrets.ORG_XTCLANG_GITHUB_MAVEN_PACKAGE_REPOSITORY_READ_WRITE }}
-
-      - name: Check Existing Tag
-        uses: mukunku/tag-exists-action@v1.4.0
-        id: checkTag
-        with:
-          tag: ${{ env.needs.setup.outputs.tag_new }}
-
-      # Publish a release if non snapshot, and we don't already have the tag. If we have the tag, we fail.
-      - name: XDK Publish Release Publication for non-snapshot and tag source
-        if: ${{ needs.setup.output.snapshot != 'true' }}
         run: |
-          echo "TAG:" ${{ steps.checkTag.outputs.exists }}
-          if [ ${{ steps.checkTag.outputs.exists }} ]; then
-            echo "FAILURE. Tag exists."
-            exit 1
-          fi
+          echo "******************** XDK_VERSION Publishing SNAPSHOT: ${{ needs.setup.outputs.xdk_version  }}"
+          ./gradlew ${{ env.gradle_options }} publishRemoteSnapshot
+
+      - name: Publish XDK Release Artifact
+        if: ${{ needs.setup.output.snapshot != 'true' }}
+        env:
+          ORG_XTCLANG_REPO_GITHUB_USER: xtclang-bot
+          ORG_XTCLANG_REPO_GITHUB_TOKEN: ${{ secrets.ORG_XTCLANG_GITHUB_MAVEN_PACKAGE_REPOSITORY_READ_WRITE }}
+        run: |
+          echo "******************* XCK_VERSION PUBLISHING RELEASE"
+          all_tags=$(git tag --list)
+          echo "ALL TAGS: $all_tags"
+          echo "NEW TAG: $tagnew"
+#          if [ ${{ steps.check-tag.outputs.exists }} ]; then
+#            echo "FAILURE. Tag exists; tag '$tagnew' created from version ${{ needs.setup.outputs.version }} as already in use."
+#            exit 1
+#          else
+#              echo "SUCCESS. We may proceeed with tag: ${{ steps.check-tag.outputs.exists }}"
+#          fi
+          
+          #echo "*** TAGGING RELEASE: ${{ needs.setup.outputs.tagnew }}"
+          #git tag --annotate $tagnew HEAD -am "XDK Release: $tagnew"
+          #git tag --list
+          #echo "*** TAGGED RELEASE $tagnew"  
+          #./gradlew ${{ env.gradle_options }} publishRemoteRelease
+          
+          # Now we know it's a release and ith as tag that hasn't been used to staap this verison before.
+          # Build the master release and publish it.
+          # Create a branch for the next version update. From a release it goes from a.b.c to a.b.(c + 1)-SNAPSHOT
+          # Modify version file accordingly, commit and create a pull request for the branch to go into master.
+          # Maybe manually merge it, but could be dangerous.
+          # TODO: Think about release branches.
